name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*.*.*
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: rustup component add rustfmt

    - run: cargo fmt --manifest-path firmware/Cargo.toml -- --check
      if: "!cancelled()"
    - run: cargo fmt --manifest-path visualizer/Cargo.toml -- --check
      if: "!cancelled()"

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: rustup component add clippy

    - run: RUSTFLAGS="-D warnings" cargo clippy --manifest-path firmware/Cargo.toml
      if: "!cancelled()"
    - run: RUSTFLAGS="-D warnings" cargo clippy --manifest-path visualizer/Cargo.toml
      if: "!cancelled()"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: rustup target add thumbv7m-none-eabi
    - run: rustup target add x86_64-unknown-linux-musl
    - run: cargo install flip-link

    - run: cargo build --release --manifest-path firmware/Cargo.toml --target thumbv7m-none-eabi
    - run: ls -lh firmware/target/thumbv7m-none-eabi/release/firmware
    - run: cargo build --release --manifest-path visualizer/Cargo.toml --target x86_64-unknown-linux-musl
    - run: ls -lh visualizer/target/x86_64-unknown-linux-musl/release/visualizer

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          firmware/target/thumbv7m-none-eabi/release/firmware
          visualizer/target/x86_64-unknown-linux-musl/release/visualizer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
